# -*- coding: utf-8 -*-
"""C8276-M.Halid Gamze

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jc4vUjRYrGEP2HKlkqizX5-dA6DNc-J_
"""

name = "Harold"
user = input("Please enter your name: ").title().strip()
if name == user:
  print("Hello, Harold! The password is : W@12")
else:
  print(f"Hello, {user}! See you later.")